### ISSUE TITLE
Docker image for simex

### ISSUE THREAD

**Issue by CFGrote** [PaNOSC-ViNYL/ViNYL-project#50] opened 2020-09-17 06:58 UTC

**Comment by cloudbustinguk** [comment] 2020-09-17 13:05
Working on a few refactors of the `simex_install.sh` install script:

```
finishing deferred symbolic links:
  SimEx-develop/Tests/python/functest/SimExTest/Backengines/WPG/paths.py -> ../../../../paths.origin.py
  SimEx-develop/Tests/python/functest/TestFiles -> ../unittest/TestFiles
  SimEx-develop/Tests/python/functest/TestUtilities -> ../unittest/TestUtilities/
  SimEx-develop/Tests/python/functest/paths.py -> ../paths.origin.py
/opt/simex_install.sh: line 13: cd: simex_platform-develop: No such file or directory
Error: error building at STEP "RUN bash /opt/simex_install.sh": error while running runtime: exit status 1
```

**Comment by cloudbustinguk** [comment] 2020-09-17 13:50
There appears to be some issues with the python installation:

1. We have an older version of Miniconda, which is 2.7. The installation scipts for SimEx call for many modules, some of which there are no wheels available, and must be built. The builds break due to using 3.x syntax:

```  running bdist_wheel                                                                                                                                                                                              /opt/miniconda/bin/python /tmp/pip-install-eC4mRp/llvmlite/ffi/build.py                                                                                                                                        
    File "/tmp/pip-install-eC4mRp/llvmlite/ffi/build.py", line 122                                                                                                                                               
      raise ValueError(msg.format(_ver_check_skip)) from e                                                                                                                                                                                                              ^                                                                                                                                                         
  SyntaxError: invalid syntax                                                                                                                                                                                    
  error: command '/opt/miniconda/bin/python' failed with exit status 1
```
and
```
 File "breathe/__init__.py", line 10                                                                                                                                                                        
        def setup(app: Sphinx):                                                                                                                                                                                                       ^                                                                                                                                                                                           
    SyntaxError: invalid syntax                 
```
and
```
on/pip-egg-info                                                                                                                                                                                                
         cwd: /tmp/pip-install-hhb84U/biopython/                                                                                                                                                                 
    Complete output (1 lines):                                                                                                                                                                                   
    Biopython requires Python 3.6 or later. Python 2.7 detected.   
```
etc..

2. A known problem with Anaconda:

```
Traceback (most recent call last):                                                                                                                                                                               
  File "/opt/miniconda/bin/conda", line 7, in <module>                                                                                                                                                           
    from conda.cli import main                                                                                                                                                                                   
ImportError: No module named conda.cli
```
.. to which Stackoverflow answers point to incorrect major versions, pathing issues, etc.
--

Will continue to work on resolving these.

**Comment by ejcjason** [comment] 2020-09-17 14:20
Does completely switching to python 3.x solve all the above issues?

**Comment by cloudbustinguk** [comment] 2020-09-17 14:22
> Does completely switching to python 3.x solve all the above issues?

Yep - will form a mini list within this issue, to deal with the new issues which have arisen.

**Comment by cloudbustinguk** [comment] 2020-09-17 14:24
Issue list:

- [ ] **CMake version bump needed**

```mkdir: created directory 'build' 
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
CMake 3.12 or higher is required.  You are running version 2.8.12.2
```
- [ ] **Workaround PEP517 module issues**

```
ERROR: Could not build wheels for pyFAI which use PEP 517 and cannot be installed directly                                                                                                                       
```

- [ ] **PyQT4 issues with 3.x conda**

```
PackagesNotFoundError: The following packages are not available from current channels:                                                                                                                           
                                                                                                                                                                                                                 
  - pyqt=4
```

**Comment by cloudbustinguk** [comment] 2020-09-17 20:09
Ok, dockerhub/github are up:

[DockerHub](https://hub.docker.com/r/cloudbusting/simex-cloudbusting)
[GitHub](https://github.com/cloudbustinguk/PaNOSC-ViNYL-SimEx)

**NOTE** - We had to use pyqt5... This is surely going to break things.

Will open another issue for this

**Comment by cloudbustinguk** [comment] 2020-09-17 20:14
EDIT: PyQT4 support *is* possible, as I just learned... but I need to downgrade the conda python from 3.7 -> 3.6.

Rebuilding now.

**Comment by ejcjason** [comment] 2020-09-17 20:51
Wait, do we have the `pyqt=4` restriction? I'm using pyqt=5.9.2 in my testing environment without problems.

**Comment by cloudbustinguk** [comment] 2020-09-17 20:54
> Wait, do we have the `pyqt=4` restriction? I'm using pyqt=5.9.2 in my testing environment without problems.

The code runs fine with PyQT5? This is great news - it's causing trouble to activate a py36 conda just so that we can have PyQT4.

**Comment by cloudbustinguk** [comment] 2020-09-17 21:00
@ejcjason You could already try and pull from the DockerHub to see if it works:

    docker pull cloudbusting/simex-cloudbusting

Would be happy for your feedback to see if anything needs work.

Beware - the image is a *monster* at ~6GB (without test data)

**Comment by shervin86** [comment] 2020-09-23 13:22
@cloudbustinguk to which branch did you push your changes?

**Comment by cloudbustinguk** [comment] 2020-09-23 13:23
Ah, it's only pushed to my own github - I informed @ejcjason to test it directly from dockerhub. I would like to make a MR once it's confirmed as working.

**Comment by shervin86** [comment] 2020-09-23 13:28
I just tried to pull from the hub, but I can't help in testing...

**Comment by shervin86** [comment] 2020-09-23 13:31
do you mind putting your changes in the branch "shervin" ? This way we can merge it as soon as it is tested

**Comment by cloudbustinguk** [comment] 2020-09-23 13:42
> I just tried to pull from the hub, but I can't help in testing...
> 3.4 GB in my docker/ directory

yes it's a big one!

**Comment by cloudbustinguk** [comment] 2020-09-23 14:24
> do you mind putting your changes in the branch "shervin" ? This way we can merge it as soon as it is tested

Done! Please see PR:  https://github.com/PaNOSC-ViNYL/SimEx/pull/226

**Comment by cloudbustinguk** [comment] 2020-09-25 15:40
@shervin86 would you mind testing the new image, and I will push changes on success?

`docker pull cloudbusting/simex`

**Comment by cloudbustinguk** [comment] 2020-09-26 16:34
@shervin86 

Hi Shervin - I've just pushed a new image to the dockerhub. This should fix the SDF issue (not being installed to the expected path).

Please first purge any old pods running/old images:

`podman stop $(podman ps -q) ; podman rm $(podman ps -qa) ; podman rmi $(podman images -q)`

Then simply attempt to run the new pod:

`podman run -it cloudbusting/simex`

Cheers

Dan

**Closed** 2021-02-26 07:28 UTC
